# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
version = "1.0.0"
category = "CAE"
title = "CAE Stage Widget icons"
description="CAE prim icons for omni.kit.widget.stage"
keywords = ["cae", "ui"]

changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.kit.widget.stage" = {}

[[python.module]]
name = "omni.cae.widget.stage_icons"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]