# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary

volumes:
  ov-cache:
  ov-local-share:
  ov-config:
  kit-cae-user-guide-data:

services:
  kit-cae:
    container_name: kit-cae
    image: kit-cae:${KIT_VERSION:-110.1.1}
    build:
      context: .
      dockerfile: docker/kit-cae/Dockerfile
      network: host
      args:
        KIT_VERSION: ${KIT_VERSION:-110.1.1}
    network_mode: host
    runtime: nvidia
    shm_size: 2gb
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      KIT_APP_FILE: ${KIT_APP_FILE:-omni.cae_streaming.kit}
      NVDA_KIT_ARGS: ${NVDA_KIT_ARGS:-}
      NVDA_KIT_NUCLEUS: ${NVDA_KIT_NUCLEUS:-}
      NVDA_KIT_BOOKMARK_NAME: ${NVDA_KIT_BOOKMARK_NAME:-}
      NVDA_KIT_BOOKMARK_VALUE: ${NVDA_KIT_BOOKMARK_VALUE:-}
    volumes:
      - ov-cache:/home/ubuntu/.cache/ov:rw
      - ov-local-share:/home/ubuntu/.local/share/ov:rw
      - ov-config:/home/ubuntu/.nvidia-omniverse:rw
      - kit-cae-user-guide-data:/home/ubuntu/kit-cae-user-guide-data:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  web-viewer:
    container_name: web-viewer
    build:
      context: ./docker/web
      network: host
    network_mode: host
    restart: unless-stopped
    depends_on:
      - kit-cae
    environment:
      ENV: ${WEB_VIEWER_ENV:-localhost}
      FORCE_WSS: ${FORCE_WSS:-}
      SIGNALING_SERVER: ${SIGNALING_SERVER:-window.location.hostname}
      SIGNALING_PORT: ${SIGNALING_PORT:-}
      MEDIA_SERVER: ${MEDIA_SERVER:-}

  nginx:
    container_name: kit-cae-nginx
    build:
      context: ./docker/nginx
    network_mode: host
    restart: unless-stopped
    depends_on:
      - kit-cae
      - web-viewer
