# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarly for displaying extension info in UI
title = "CAE Algorithms Warp"
description = "Extension that provides CAE visualization and processing algorithms using NVIDIA Warp for GPU acceleration."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# One of categories for UI.
category = "CAE"

# Keywords for the extension
keywords = ["kit", "cae", "warp", "algorithms"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[dependencies]
"omni.usd" = {}
"omni.cae.data" = {}
"omni.cae.schema" = {}
"omni.cae.algorithms.core" = {}
"omni.warp.core" = {}
"omni.kit.commands" = { optional = true }

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "omni.cae.algorithms.warp"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]

[[test]]

dependencies = [
    "omni.cae.testing",
    "omni.cae.cgns",
    "omni.cae.sids",
    "omni.kit.primitive.mesh",
]