# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
version = "1.0.0"
title = "CAE Scae"
description = "Extension that provides .scae data delegate support for manifest/binary CAE datasets."
readme  = "docs/README.md"
category = "CAE"
keywords = ["kit", "cae", "scae"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"

[dependencies]
"omni.usd" = {}
"omni.cae.schema" = {}
"omni.cae.data" = {}
"omni.client" = {}

[[python.module]]
name = "omni.cae.delegate.scae"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]

[[test]]
dependencies = [
    "omni.cae.testing",
]
