# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
title = "Omni CAE VTK Libs"
version = "1.0.0"
description = "VTK libraries"
category = "Internal"
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
keywords = ["kit", "cae", "extension"]
readme  = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/kit-cae"

[dependencies]
"omni.cae.pipapi" = {}

[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.cae.vtk_libs"
name = "omni.cae.vtk_libs"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
