# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
title = "CAE Material Library"
version = "1.0.1"  # Semantic Versionning is used: https://semver.org/
description = "The simplest python extension example. Use it as a starting point for your extensions."
category = "Example"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "example", "extension"]  # Search keywords for the Extension Manager
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI

[dependencies]
"omni.client" = {}

[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.cae.material_library"
name = "omni.cae.material_library"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
]

args = [
]